import {  Poppins } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  variable: "--popppins",
  subsets: ["latin"],
  weight:["500","600","800"]
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme='light'
      className={`h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${poppins.className} `}>{children}</body>
    </html>
  );
}
